name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  api-lint:
    name: API - Ruff
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: apps/api/pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"

      - name: Ruff check
        run: ruff check .
